# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-18 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activity',
            field=models.TextField(default='No activity.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='gold',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='GameData',
        ),
    ]
