# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-23 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_auto_20170823_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default='12/31/1999'),
        ),
    ]
