# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-21 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hero',
            name='hero_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='power',
            name='power',
            field=models.CharField(default='', max_length=50),
        ),
    ]
