# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-22 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('heroes_app', '0002_auto_20170821_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='likes',
            new_name='allLikes',
        ),
        migrations.AddField(
            model_name='hero',
            name='userLikes',
            field=models.ManyToManyField(related_name='heroLikes', to='login_app.User'),
        ),
    ]
